# Generated by Django 5.2.1 on 2025-08-04 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'JOB_SEEKER'}, on_delete=django.db.models.deletion.CASCADE, to='account.customuser')),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
